<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Monti Hall Paradox</title>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Проверка парадокса Монти Холла</h1>
        <h3 class="text-center">Данный сайт предназначен для проверки парадокса Монти Холла</h3>
        <br>
        <div class="text-justify">
            Парадокс Монти Холла — одна из известных задач теории вероятностей, решение которой, 
            на первый взгляд, противоречит здравому смыслу. Эта задача не является парадоксом в узком 
            смысле этого слова, так как не содержит в себе противоречия, она называется парадоксом потому, 
            что ее решение может показаться неожиданным. Более того, многим людям бывает сложно принять 
            правильное решение даже после того, как его им рассказали.
        </div>
        <br>
        <div class="text-justify"><i>
            Представьте, что вы стали участником игры, в которой вам нужно выбрать одну из трёх дверей. 
            За одной из дверей находится автомобиль, за двумя другими дверями — козы. Вы выбираете одну из дверей, 
            например, номер 1, после этого ведущий, который знает, где находится автомобиль, а где — козы, 
            открывает одну из оставшихся дверей, например, номер 3, за которой находится коза. После этого он 
            спрашивает вас — не желаете ли вы изменить свой выбор и выбрать дверь номер 2? Увеличатся ли ваши 
            шансы выиграть автомобиль, если вы примете предложение ведущего и измените свой выбор?
        </i></div>
        <br>
        <div class="text-justify">
            <ul>
                <strong>Есть ряд ограничений:</strong>
                <li>автомобиль равновероятно размещён за любой из трёх дверей;</li>
                <li>ведущий знает, где находится автомобиль;</li>
                <li>ведущий в любом случае обязан открыть дверь с козой (но не ту, которую выбрал игрок) и предложить игроку изменить выбор;</li>
                <li>если у ведущего есть выбор, какую из двух дверей открыть, он выбирает любую из них с одинаковой вероятностью.</li>
            </ul>
        </div>
        <div class="text-justify">
            На нашем сайте мы проверим правдоподобность данной теории на практике. Нажмите кнопку "Начать" после чего выберите 
            любую из дверей на ваш выбор. Система автоматически для начала откроет любую из оставшихся дверей где нет автомобиля, 
            а затем поменяет ваш выбор двери на другую оставшуюся дверь, после чего откроются обе оставшиеся двери и станет известно 
            где находился автомобиль, а результаты будут сложены с результатами других опытов и занесены в базу.
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <form action="/run" method="get">
                <input class="btn btn-primary" type="submit" value="Начать проверку">
            </form>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>