<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Monti Hall Paradox</title>
</head>
<body>
    <header class="header text-center">
        <h1>Выберите дверь</h1>
    </header>
    <main class="d-flex flex-wrap-reverse align-items-end justify-content-center">
        <div class="doors d-flex flex-wrap justify-content-center">
            <a href="/" rel="nofollow">
                <div class="door door-1 d-flex justify-content-center align-items-center">
                    <span class="door__title text-uppercase">Дверь 1</span>
                    <div class="door__knob"></div>
                    <div class="door__hinge door__hinge-1 "></div>
                    <div class="door__hinge door__hinge-2"></div>
                </div>
            </a>
            <a href="/" rel="nofollow">
                <div class="door door-2 d-flex justify-content-center align-items-center">
                    <span class="door__title text-uppercase">Дверь 2</span>
                    <div class="door__knob"></div>
                    <div class="door__hinge door__hinge-1 "></div>
                    <div class="door__hinge door__hinge-2"></div>
                </div>
            </a>
            <a href="/" rel="nofollow">
                <div class="door door-3 d-flex justify-content-center align-items-center">
                    <span class="door__title text-uppercase">Дверь 3</span>
                    <div class="door__knob"></div>
                    <div class="door__hinge door__hinge-1 "></div>
                    <div class="door__hinge door__hinge-2"></div>
                </div>
            </a>
        </div>
        <div class="static-info d-flex justify-content-center">
            <h3>Статистика:</h3>
        </div>
    </main>
    <footer>

    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>