<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css?<?=filemtime('style.css')?>">
    <title>Monti Hall Paradox</title>
</head>
<body>
    
    <header class="header text-center">
        <h1>Результат</h1>
    </header>
    <main class="d-flex flex-wrap-reverse align-items-end justify-content-center">
        <div class="doors d-flex flex-wrap justify-content-center">
            <a href="/doors" rel="nofollow">
                <div class="door door-1 d-flex flex-column justify-content-center align-items-center">
                    <span class="door__title text-uppercase">Дверь 1</span>
                    <div class="door__knob"></div>
                    <div class="door__hinge door__hinge-1 "></div>
                    <div class="door__hinge door__hinge-2"></div>
                    <img src="img/yakub-open.jpeg" hidden>
                </div>
                <div class="opened-door opened-door-1 d-none flex-column justify-content-center align-items-center">
                    <span class="opened-door__title text-uppercase">Дверь 1</span>
                    <?php if ($doorWithCar === 1) : ?>
                        <img src="img/auto.jpeg">
                    <?php else : ?>
                        <img src="img/koza.jpeg">
                    <?php endif; ?>
                    <div class="opened-door__edge"></div>
                    <div class="opened-door__knob-cap"></div>
                    <div class="opened-door__knob-leg"></div>
                    <div class="opened-door__hinge opened-door__hinge-1 "></div>
                    <div class="opened-door__hinge opened-door__hinge-2"></div>
                </div>
            </a>
            <a href="/doors" rel="nofollow">
                <div class="door door-2 d-flex flex-column justify-content-center align-items-center">
                    <span class="door__title text-uppercase">Дверь 2</span>
                    <div class="door__knob"></div>
                    <div class="door__hinge door__hinge-1 "></div>
                    <div class="door__hinge door__hinge-2"></div>
                    <img src="img/yakub-open.jpeg" hidden>
                </div>
                <div class="opened-door opened-door-2 d-none flex-column justify-content-center align-items-center">
                    <span class="opened-door__title text-uppercase">Дверь 2</span>
                    <?php if ($doorWithCar === 2) : ?>
                        <img src="img/auto.jpeg">
                    <?php else : ?>
                        <img src="img/koza.jpeg">
                    <?php endif; ?>
                    <div class="opened-door__edge"></div>
                    <div class="opened-door__knob-cap"></div>
                    <div class="opened-door__knob-leg"></div>
                    <div class="opened-door__hinge opened-door__hinge-1 "></div>
                    <div class="opened-door__hinge opened-door__hinge-2"></div>
                </div>
            </a>
            <a href="/doors" rel="nofollow">
                <div class="door door-3 d-flex flex-column justify-content-center align-items-center">
                    <span class="door__title text-uppercase">Дверь 3</span>
                    <div class="door__knob"></div>
                    <div class="door__hinge door__hinge-1 "></div>
                    <div class="door__hinge door__hinge-2"></div>
                    <img src="img/yakub-open.jpeg" hidden>
                </div>
                <div class="opened-door opened-door-3 d-none flex-column justify-content-center align-items-center">
                    <span class="opened-door__title text-uppercase">Дверь 3</span>
                    <?php if ($doorWithCar === 3) : ?>
                        <img src="img/auto.jpeg">
                    <?php else : ?>
                        <img src="img/koza.jpeg">
                    <?php endif; ?>
                    <div class="opened-door__edge"></div>
                    <div class="opened-door__knob-cap"></div>
                    <div class="opened-door__knob-leg"></div>
                    <div class="opened-door__hinge opened-door__hinge-1 "></div>
                    <div class="opened-door__hinge opened-door__hinge-2"></div>
                </div>
            </a>
        </div>
        <div class="nav d-flex flex-column">
            <div class="static-info d-flex flex-column">
                <h3>Статистика:</h3>
                <div>Всего успешных выборов: <?= $numberOfAllGoodRounds ?></div>
                <div>Общее количество попыток: <?= $numberOfAllRounds ?></div>
                <div><b>Общий процент успешности: <?= $roundedAllPersent ?></b></div>
                <div>Ваших успешных выборов: <?= $numberOfSessionGoodRounds ?></div>
                <div>Общее количество ваших попыток: <?= $numberOfSessionRounds ?></div>
                <div><b>Общий процент ваших успешных выборов: <?= $roundedSessionPersent ?></b></div>
            </div>
            <div class="destroy-button">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
                    Очистить историю статистики
                </button>
            </div>
            <div class="about-program">
                <form action="/about" method="get">
                    <input class="btn btn-primary" type="submit" value="Комментарии к тестовому заданию">
                </form>               
            </div>
        </div>
    </main>
    <footer class="footer d-flex justify-content-center container">
        Если же все равно не верится что так может быть, то попробуйте представить себе ту же задачу с тем лишь изменением, что дверей
        не 3, а 1000. А ведущий после вашего выбора откроет 998 других дверей, за которыми точно нет машины. В таком случае вы оставите
        неизменным свой выбор? А ведь принцип тот же :)
    </footer>
    <div id="data-for-script">
        <div id="chosenDoor"><?= $chosenDoor ?></div>
        <div id="openedDoor"><?= $openedDoor ?></div>
        <div id="nextDoor"><?= $nextDoor ?></div>
        <div id="doorWithCar"><?= $doorWithCar ?></div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Подтверждение удаления данных статистики</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Вы уверены что хотите удалить данные статистики? Если да, то введите пароль и нажмите кнопку "Очистить".
            </div>
            <form action="/destroy" method="post">
                <div class="modal-footer">
                        <input type="hidden" name="_METHOD" value="DELETE">
                        <label class="d-flex flex-row flex-nowrap align-items-baseline">
                            <span>Пароль:&nbsp;&nbsp;</span>
                            <input type="password" name="password" id="">
                        </label>
                        <input class="btn btn-danger" type="submit" value="Очистить">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">отмена</button>
                </div>
            </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="script.js?<?=filemtime('script.js')?>"></script>
</body>
</html>